version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - almat_net

  app:
    build: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - almat_net

  worker:
    build: .
    command: ["celery", "-A", "celery_app.celery", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db
    networks:
      - almat_net

volumes:
  postgres_data:

networks:
  almat_net:
    driver: bridge
